# Generated by Django 5.0 on 2024-02-25 09:28

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0004_comment_active_emailqueue_active_group_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='images',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='post_image'),
        ),
    ]
