# Generated by Django 5.0 on 2024-02-25 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0005_post_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_block',
            field=models.BooleanField(default=False),
        ),
    ]
