# Generated by Django 5.0 on 2024-02-29 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0009_notification_group_notification_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='closed_at',
            field=models.DateTimeField(null=True),
        ),
    ]
